name: Deploy Lambdas

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPO: neon-integrations

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build-push-deploy:
    if: ${{ github.repository == 'asmbly-makerspace/NeonIntegrations' }}
    runs-on: ubuntu-latest
    name: Build, push, and deploy Lambdas

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        platforms: linux/arm64
        context: .
        provenance: false
        target: production
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest

    - name: Deploy alta-open-update
      uses: aws-actions/aws-lambda-deploy@v1.1.0
      with:
        function-name: alta-open-update
        package-type: Image
        architectures: arm64
        image-uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest
        timeout: 20
        image-config: '{"Command": ["alta_open_lambda.lambda_function.lambda_handler"]}'

    - name: Deploy daily-maintenance
      uses: aws-actions/aws-lambda-deploy@v1.1.0
      with:
        function-name: daily-maintenance
        package-type: Image
        architectures: arm64
        image-uri: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest
        timeout: 900
        image-config: '{"Command": ["daily_maintenance_lambda.lambda_function.lambda_handler"]}'
