name: Run pytest
jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: test
          load: true
          tags: tests:latest

      - name: Run tests
        run: docker run --rm tests:latest -v
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - '*'
